# Generated by Django 3.0.3 on 2020-02-23 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='expdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
