# Generated by Django 3.0.3 on 2020-02-24 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain_app', '0003_auto_20200224_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainflag',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domainflag', to='domain_app.Domain'),
        ),
    ]
